name: Bandit
description: Github Action for the Python Bandit tool
author: Harvey Rogers
inputs:
  paths:
    description: the path(s) to run against
    required: true
  config-file:
    description: bandit config file
    default: bandit.yml
  bandit-path:
    description: path to bandit executable
    default: bandit
  github-token:
    description: GitHub token for posting annotations
    required: false
runs:
  using: node12
  main: dist/index.js
