name: Bandit
description: Github Action for the Python Bandit tool
author: Harvey Rogers
inputs:
  paths:
    description: the path(s) to run against
    required: true
  config-file:
    description: bandit config file
    required: false
  bandit-path:
    description: path to bandit executable
    default: bandit
  github-token:
    description: GitHub token for posting annotations
    required: false
  annotation-levels:
    description: |
      Rules for choosing GitHub annotation levels. Format is `<severity>-<confidence>|<annotation level>`.
      See https://developer.github.com/v3/checks/runs/#annotations-object for GitHub docs on annotations.
    default: |
      HIGH-HIGH|failure
      HIGH-MEDIUM|failure
      HIGH-LOW|warning
      MEDIUM-HIGH|failure
      MEDIUM-MEDIUM|warning
      MEDIUM-LOW|notice
      LOW-HIGH|notice
      LOW-MEDIUM|notice
      LOW-LOW|notice
runs:
  using: node12
  main: dist/index.js
